const secured = (summary: string) => ({
  summary,
  security: [{ cognitoAdmin: [] }],
  responses: { "200": { description: "Success" }, "400": { description: "Invalid request" }, "401": { description: "Authentication required" }, "403": { description: "Access denied" }, "404": { description: "Not found" }, "409": { description: "Revision or idempotency conflict" } },
});

export const adminApiOpenApi = {
  openapi: "3.1.0",
  info: { title: "BDR Portal Admin API", version: "1.0.0" },
  paths: {
    "/admin/openapi.json": { get: secured("Get this OpenAPI contract") },
    "/admin/auth/sessions": { post: secured("Establish an application administrator session") },
    "/admin/auth/session": { delete: secured("Revoke the current administrator session") },
    "/admin/organizations": { get: secured("List organizations"), post: secured("Create an organization") },
    "/admin/organizations/{organizationId}": { get: secured("Get an organization"), patch: secured("Update organization metadata") },
    "/admin/organizations/{organizationId}/users": { get: secured("List client users") },
    "/admin/organizations/{organizationId}/users/{userId}/revoke": { post: secured("Revoke a client user") },
    "/admin/organizations/{organizationId}/users/{userId}/replace-identity": { post: secured("Invite a replacement identity") },
    "/admin/organizations/{organizationId}/invitations": { get: secured("List invitations"), post: secured("Invite a client user") },
    "/admin/organizations/{organizationId}/invitations/{invitationId}/resend": { post: secured("Resend an invitation") },
    "/admin/organizations/{organizationId}/invitations/{invitationId}/cancel": { post: secured("Cancel an invitation") },
    "/admin/organizations/{organizationId}/projects": { get: secured("List projects"), post: secured("Create a project") },
    "/admin/organizations/{organizationId}/projects/{projectId}": { get: secured("Get a project"), patch: secured("Update project metadata") },
    "/admin/organizations/{organizationId}/projects/{projectId}/archive-preview": { post: secured("Preview project archive impact") },
    "/admin/organizations/{organizationId}/projects/{projectId}/archive": { post: secured("Archive a project") },
    "/admin/organizations/{organizationId}/projects/{projectId}/restore-preview": { post: secured("Preview project restore impact") },
    "/admin/organizations/{organizationId}/projects/{projectId}/restore": { post: secured("Restore a project") },
    "/admin/organizations/{organizationId}/projects/{projectId}/inspections": { get: secured("List inspections"), post: secured("Create an inspection") },
    "/admin/organizations/{organizationId}/projects/{projectId}/inspections/{inspectionId}": { get: secured("Get an inspection"), patch: secured("Update draft inspection metadata") },
    "/admin/organizations/{organizationId}/projects/{projectId}/inspections/{inspectionId}/archive-preview": { post: secured("Preview inspection archive impact") },
    "/admin/organizations/{organizationId}/projects/{projectId}/inspections/{inspectionId}/archive": { post: secured("Archive an inspection") },
    "/admin/organizations/{organizationId}/projects/{projectId}/inspections/{inspectionId}/restore-preview": { post: secured("Preview inspection restore impact") },
    "/admin/organizations/{organizationId}/projects/{projectId}/inspections/{inspectionId}/restore": { post: secured("Restore an inspection") },
    "/admin/organizations/{organizationId}/projects/{projectId}/inspections/{inspectionId}/reports": { get: secured("List report classifications") },
    "/admin/organizations/{organizationId}/projects/{projectId}/inspections/{inspectionId}/reports/{reportType}": { patch: secured("Change a draft report classification") },
    "/admin/organizations/{organizationId}/projects/{projectId}/inspections/{inspectionId}/publish": { post: secured("Publish a draft inspection and its selected reports") },
    "/admin/organizations/{organizationId}/projects/{projectId}/inspections/{inspectionId}/reports/{reportType}/publish": { post: secured("Publish or replace one report on a published inspection") },
    "/admin/organizations/{organizationId}/projects/{projectId}/inspections/{inspectionId}/reports/{reportType}/versions": { get: secured("List retained report versions") },
    "/admin/organizations/{organizationId}/projects/{projectId}/inspections/{inspectionId}/reports/{reportType}/withdraw": { post: secured("Withdraw a published report") },
    "/admin/organizations/{organizationId}/documents/how-to-read": { get: secured("Get How to Read metadata"), put: secured("Initialize How to Read metadata") },
    "/admin/organizations/{organizationId}/documents/how-to-read/publish": { post: secured("Publish How to Read") },
    "/admin/organizations/{organizationId}/documents/how-to-read/replace": { post: secured("Replace How to Read") },
    "/admin/organizations/{organizationId}/documents/how-to-read/versions": { get: secured("List retained How to Read versions") },
    "/admin/organizations/{organizationId}/upload-sessions": { post: secured("Create an immutable upload session") },
    "/admin/organizations/{organizationId}/upload-sessions/{uploadSessionId}/status": { post: secured("Read an upload session through its immutable tenant locator") },
    "/admin/organizations/{organizationId}/upload-sessions/{uploadSessionId}/complete": { post: secured("Verify a completed upload") },
    "/admin/organizations/{organizationId}/upload-sessions/{uploadSessionId}/upload-url": { post: secured("Recover an interrupted upload or issue a replacement URL") },
  },
  components: {
    securitySchemes: { cognitoAdmin: { type: "http", scheme: "bearer", bearerFormat: "JWT" } },
  },
} as const;
